// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhrR4m5xkFU8JS3ObRpeWeaVOV4KNqtgY',
    appId: '1:435634185408:web:fccde9ccdf9cf800467925',
    messagingSenderId: '435634185408',
    projectId: 'zonemaster-366a1',
    authDomain: 'zonemaster-366a1.firebaseapp.com',
    storageBucket: 'zonemaster-366a1.firebasestorage.app',
    measurementId: 'G-YQE3WXKR8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1MyRb_m07x_YbEk4pEwPRhZoW9Z_Kydk',
    appId: '1:435634185408:android:871992c2281a9487467925',
    messagingSenderId: '435634185408',
    projectId: 'zonemaster-366a1',
    storageBucket: 'zonemaster-366a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4xwOZO9qqAlP1URM5tZRV4OrIufalE7w',
    appId: '1:435634185408:ios:1b6ddaba0f0f9179467925',
    messagingSenderId: '435634185408',
    projectId: 'zonemaster-366a1',
    storageBucket: 'zonemaster-366a1.firebasestorage.app',
    iosBundleId: 'com.example.testappbita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4xwOZO9qqAlP1URM5tZRV4OrIufalE7w',
    appId: '1:435634185408:ios:1b6ddaba0f0f9179467925',
    messagingSenderId: '435634185408',
    projectId: 'zonemaster-366a1',
    storageBucket: 'zonemaster-366a1.firebasestorage.app',
    iosBundleId: 'com.example.testappbita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhrR4m5xkFU8JS3ObRpeWeaVOV4KNqtgY',
    appId: '1:435634185408:web:738e9a9656cb3605467925',
    messagingSenderId: '435634185408',
    projectId: 'zonemaster-366a1',
    authDomain: 'zonemaster-366a1.firebaseapp.com',
    storageBucket: 'zonemaster-366a1.firebasestorage.app',
    measurementId: 'G-KP9SSLPZKH',
  );
}
